### ISSUE TITLE
updated for Xcode 7.2

### ISSUE THREAD

**Issue by idcrook** [quillford/OctoControl#1]
Glad you shared this project!

Not sure if you are still touching this codebase. I wanted to get it running for myself, so made some changes in a fork today.  

the edits I made were in related to 
1. Swift language changes
2. Network security changes.  
   - Apple now by default requires TLS accesses for Web API calls (App Transport Security).  I disabled, since it was going to be more work-- than I had time for-- to deal with the self-signed certs that OctoPi uses.

Let me know if you were interested in the changes for inclusion back.  https://github.com/dpcrook/OctoControl-iOS

**Comment by narner** [comment]
@dpcrook I'm glad I found your fork! Btw, when I downloaded a zip I got an error of "No Such Module Starscream" (leaving a comment here as I can't seem to make an issue on your own fork).

**Comment by idcrook** [comment]
Ah.  I changed it to be a `git submodule` in my clone, instead of checking in the full framework.  So you'll want to do a git operation to pull in the submodule.  Probably, it should be made a CocoaPod to manage this external dependency.

Also, I just enabled 'Issues' in the repository, if you still wanted to open an issue.

**Comment by narner** [comment]
@dpcrook Got it working now I think :) But sure, I'll open an issue for record-keeping sake. BTW, what's your email? Have a few questions about this all actually...

**Comment by idcrook** [comment]
I am going to close this issue, as we are living in a Swift 3.0 / Xcode 8.1 world :)
